language: php
php:
    - 5.6
    - 7.0
    - 7.1

before_script:
    - composer install --no-interaction
    - if [ $TRAVIS_PHP_VERSION == "7.0" ]; then coverage="-p phpdbg --coverage tests/report.xml --coverage-src src"; fi

script:
    - ./vendor/bin/tester tests -s -p php -c tests/unix.ini $coverage

after_script:
    # Report Code Coverage
    - >
      if [ "$coverage" != "" ]; then
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      && php coveralls.phar --verbose --config tests/.coveralls.yml
      || true; fi